# Generated by Django 4.0.5 on 2022-07-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_phonenumorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumorder',
            old_name='sratus',
            new_name='status',
        ),
    ]
